### ISSUE TITLE
Local installation of external javascript libraries (morris.js)

### ISSUE THREAD

**Issue by abrasat** [mpolinowski/nodered-dashboard-getting-started#1]
Thank you for the very useful tutorial.
I have a scenario where node-red would be used in a intranet environment (no internet, thus no CDN). How could the external javascript libraries needed in ui_template nodes (morris.js) and their dependencies be locally installed in node-red ? What files are exactly needed to be able to use morris.js charts?

**Comment by mpolinowski** [comment]
Hi,

and thank you :)

So Node-RED runs offline - but you already have the dashboard installed? If so, then there is a quick-and-dirty solution. Instead of linking in the CDN you can add the content of the JS file inside a script tag. Would that be a solution for your use-case?

**Comment by mpolinowski** [comment]
I am not sure if this worked for you or not - but I am closing this issue for now because of inactivity. Please feel free to ping me if you still have an issue with your setup.

**Comment by abrasat** [comment]
Yes, it worked. Thank you.
